name = "webtoon-converter"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
[pages_build_output_dir]
directory = ".vercel/output/static"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
